### ISSUE TITLE
Add Spread Operator in component

### ISSUE THREAD

**Issue by godrix** [muhammadwafa/expo-fast-image#1]
adding ...props add support a resizeMode="contain" 

export default memo(({ uri, cacheKey, style, **...props** }) => {

    const encodedLink = encodeURI(uri);
    const [imgUrl, setUrl] = useState(`${FileSystem.cacheDirectory}${cacheKey}`);

    useEffect(() => {

        (async () => {

            // let imgExt = findExt(encodedLink);
            // if (!imgExt || imgExt.length < 1) { return };

            const cacheFileUri = `${FileSystem.cacheDirectory}${cacheKey}`;
            let imgInCache = await checkImageInCache(cacheFileUri);

            if (!imgInCache.exists) {
                let cached = await cacheImage(encodedLink, cacheFileUri, () => { });
                if (cached) { setUrl(`${cacheFileUri}/m`); setUrl(cached); }
            }
        })();

    }, []);

    return <Image source={{ uri: imgUrl }} style={style} **{...props}** />
});`
`

**Comment by muhammadwafa** [comment]
Ok sure thank you for feedback
